### ISSUE TITLE
Bare Hands Kill Bug

### ISSUE THREAD

**Issue by beboom** [CAD97/SpawnerCraft2#10]
I found a bug in the latest 1.7.10 version of this mod.
When a mob was killed using bare hands instead of sword or some tool, the player connection was closed and the follow error message appeared in the log:

```
[23:58:05] [Server thread/WARN]: Failed to handle packet for /192.168.10.12:10502
java.lang.NullPointerException
    at cad97.spawnercraft.handler.DropsListener.onMobDrops(DropsListener.java:26) ~[DropsListener.class:?]
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_26_DropsListener_onMobDrops_LivingDropsEvent.invoke(.dynamic) ~[?:?]
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) ~[EventBus.class:?]
    at net.minecraftforge.common.ForgeHooks.onLivingDrops(ForgeHooks.java:308) ~[ForgeHooks.class:?]
    at net.minecraft.entity.EntityLivingBase.func_70645_a(EntityLivingBase.java:939) ~[sv.class:?]
    at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:855) ~[sv.class:?]
    at net.minecraft.entity.player.EntityPlayer.func_71059_n(EntityPlayer.java:1232) ~[yz.class:?]
    at net.minecraft.network.NetHandlerPlayServer.func_147340_a(NetHandlerPlayServer.java:821) ~[nh.class:?]
    at net.minecraft.network.play.client.C02PacketUseEntity.func_148833_a(SourceFile:55) ~[ja.class:?]
    at net.minecraft.network.play.client.C02PacketUseEntity.func_148833_a(SourceFile:10) ~[ja.class:?]
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?]
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
```

**Comment by CAD97** [comment]
Um. Oops. I thought that was null protected... At least it will be a quick fix. I'll push it before tomorrow.

**Comment by CAD97** [comment]
That would be why it wasn't caught. In 1.8 singleplayer FML catches the exception and prevents it from doing anything. I just will need to null-guard the check of the player's held item and we should be good.

**Comment by CAD97** [comment]
I'll make a build within the next hour. I've got to go do life right now.
