### ISSUE TITLE
Crash server 1.8 - Spawnercraft 2.3

### ISSUE THREAD

**Issue by ricardOwner** [CAD97/SpawnerCraft2#13]
```
net.minecraftforge.fml.common.LoaderException: java.lang.NoSuchFieldError: name
    at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:163)
    at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:738)
    at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:97)
    at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:360)
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:210)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:438)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoSuchFieldError: name
    at cad97.spawnercraft.init.ModRecipes.registerEggCrafting(ModRecipes.java:56)
    at cad97.spawnercraft.init.ModRecipes.init(ModRecipes.java:21)
    at cad97.spawnercraft.SpawnerCraft2.postInit(SpawnerCraft2.java:46)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:537)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
    at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:736)
    ... 5 more
```

**Comment by CAD97** [comment]
I can't seem to replicate this crash. Could you please provide a mod list that you have installed so I have a better chance of replicating this so that I can fix it?

If you'd really like to help, I'd benefit from a minimum viable test case -- e.g. the minimum setup that causes this crash. Unfortunately I cannot see where this crash happens from the stack trace due to its nature.

**Comment by CAD97** [comment]
This issue will be closed in one week if no response is received. Even if it is closed, please leave a comment if it is still occurring with a reproducible test case and the issue will be reopened.

**Comment by CAD97** [comment]
I suspect you were not using a recent enough version of Forge. At the time this was posted, I was using a feature added since the Recommended build. Between then and now many Recommended Builds have passed, and I'm uploading a version for 1.8.9 currently. This error should not if you are using a 1.8.9 forge and the 1.8.9 mod.
